apiVersion: environment.cloudbees.com/v1alpha1
kind: GitRepository
metadata:
  name: cbci-previews-demo-insurance-frontend                             
  namespace: previews
spec:
  url: https://github.com/cbci-previews-demo/insurance-frontend.git
  apiTokenSecretRef:
    name: beedemo-dev-github-token
  autoUpdateContexts:                           
  - default
